name: SonarQube Scan
on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:  
jobs:
  sonarQube:
    name: SonarQube-Job
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout source repo
        uses: actions/checkout@v1
        with:
          ref: '${{ github.head_ref }}'
    
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3.3.0
        with:
          repository: EnterpriseDB/edb-github-actions.git
          ref: master
          token: ${{ secrets.GH_SLONIK }}
          path: .github/actions/edb-github-actions
          
      - name: SonarQube Scan
        uses: ./.github/actions/edb-github-actions/sonarqube
        with:
            REPO_NAME: '${{github.event.repository.name}}'
            SONAR_PROJECT_KEY: EnterpriseDB_repmgr
            SONAR_URL: '${{secrets.SONARQUBE_URL}}'
            SONAR_LOGIN: '${{secrets.SONARQUBE_LOGIN}}'
            PULL_REQUEST_KEY: '${{github.event.number}}'
            PULL_REQUEST_BRANCH: '${{github.head_ref}}'
            PULL_REQUEST_BASE_BRANCH: '${{github.base_ref}}'
            REPO_DEFAULT_BRANCH: '${{github.event.repository.default_branch}}'
            REPO_EXCLUDE_FILES: '*properties*,**/src/test/**/*,**/*.sql,**/docs/**/*,**/*/*.java'